/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Lexer.lex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\15\1\4\1\2\1\12\1\12\1\1\16\15\4\0\1\3\1\51"+
    "\1\17\1\11\1\15\1\15\1\52\1\16\1\63\1\64\1\61\1\57"+
    "\1\50\1\60\1\67\1\14\1\10\11\6\1\45\1\47\1\55\1\46"+
    "\1\54\1\56\1\15\5\5\1\21\5\5\1\5\7\5\1\20\6\5"+
    "\1\70\1\15\1\71\1\62\1\7\1\0\1\23\1\41\1\34\1\33"+
    "\1\27\1\36\1\5\1\43\1\24\1\5\1\42\1\26\1\22\1\25"+
    "\1\40\1\31\1\44\1\32\1\37\1\30\1\35\5\5\1\65\1\53"+
    "\1\66\1\0\6\15\1\13\32\15\1\0\1\15\4\15\1\0\1\15"+
    "\2\0\1\15\1\15\1\0\1\15\7\0\1\15\2\15\2\0\1\15"+
    "\1\15\3\0\1\15\27\15\1\0\37\15\1\0\u01ca\15\4\0\14\15"+
    "\16\0\5\15\7\0\1\15\1\0\1\15\21\0\165\15\1\0\2\15"+
    "\2\0\4\15\1\15\7\0\1\15\1\15\3\15\1\0\1\15\1\0"+
    "\24\15\1\0\123\15\1\0\213\15\1\0\5\15\2\0\236\15\11\0"+
    "\46\15\2\0\1\15\6\15\1\0\47\15\1\0\2\15\4\0\1\15"+
    "\1\0\55\15\1\15\1\15\1\15\2\15\1\15\2\15\1\15\1\15"+
    "\10\0\33\15\5\0\3\15\2\15\13\0\5\15\4\0\2\15\1\15"+
    "\2\15\2\0\13\15\1\15\2\0\2\15\112\15\4\15\146\15\1\15"+
    "\11\15\1\0\12\15\1\0\23\15\2\0\1\15\16\15\1\0\74\15"+
    "\2\0\145\15\16\0\66\15\1\0\3\15\1\15\5\0\56\15\2\0"+
    "\17\15\1\0\34\15\2\0\1\15\101\0\1\15\1\0\13\15\67\0"+
    "\33\15\1\0\144\15\2\15\12\15\1\15\7\15\1\0\7\15\1\0"+
    "\3\15\1\0\10\15\2\0\2\15\2\0\26\15\1\0\7\15\1\0"+
    "\1\15\3\0\4\15\2\0\11\15\2\0\2\15\2\0\4\15\10\0"+
    "\1\15\4\0\2\15\1\0\5\15\2\0\16\15\7\0\1\15\5\0"+
    "\3\15\1\0\6\15\4\0\2\15\2\0\26\15\1\0\7\15\1\0"+
    "\2\15\1\0\2\15\1\0\2\15\2\0\1\15\1\0\5\15\4\0"+
    "\2\15\2\0\3\15\3\0\1\15\7\0\4\15\1\0\1\15\7\0"+
    "\20\15\13\0\3\15\1\0\11\15\1\0\3\15\1\0\26\15\1\0"+
    "\7\15\1\0\2\15\1\0\5\15\2\0\12\15\1\0\3\15\1\0"+
    "\3\15\2\0\1\15\17\0\4\15\2\0\12\15\1\15\1\15\17\0"+
    "\3\15\1\0\10\15\2\0\2\15\2\0\26\15\1\0\7\15\1\0"+
    "\2\15\1\0\5\15\2\0\11\15\2\0\2\15\2\0\3\15\10\0"+
    "\2\15\4\0\2\15\1\0\5\15\2\0\12\15\1\0\1\15\20\0"+
    "\2\15\1\0\6\15\3\0\3\15\1\0\4\15\3\0\2\15\1\0"+
    "\1\15\1\0\2\15\3\0\2\15\3\0\3\15\3\0\14\15\4\0"+
    "\5\15\3\0\3\15\1\0\4\15\2\0\1\15\6\0\1\15\16\0"+
    "\12\15\11\0\1\15\7\0\3\15\1\0\10\15\1\0\3\15\1\0"+
    "\27\15\1\0\12\15\1\0\5\15\3\0\10\15\1\0\3\15\1\0"+
    "\4\15\7\0\2\15\1\0\2\15\6\0\4\15\2\0\12\15\22\0"+
    "\2\15\1\0\10\15\1\0\3\15\1\0\27\15\1\0\12\15\1\0"+
    "\5\15\2\0\11\15\1\0\3\15\1\0\4\15\7\0\2\15\7\0"+
    "\1\15\1\0\4\15\2\0\12\15\1\0\2\15\17\0\2\15\1\0"+
    "\10\15\1\0\3\15\1\0\51\15\2\0\10\15\1\0\3\15\1\0"+
    "\5\15\10\0\1\15\10\0\4\15\2\0\12\15\12\0\6\15\2\0"+
    "\2\15\1\0\22\15\3\0\30\15\1\0\11\15\1\0\1\15\2\0"+
    "\7\15\3\0\1\15\4\0\6\15\1\0\1\15\1\0\10\15\22\0"+
    "\2\15\1\15\14\0\72\15\4\0\20\15\1\15\12\15\2\15\45\0"+
    "\2\15\1\0\1\15\2\0\2\15\1\0\1\15\2\0\1\15\6\0"+
    "\4\15\1\0\7\15\1\0\3\15\1\0\1\15\1\0\1\15\2\0"+
    "\2\15\1\0\15\15\1\0\3\15\2\0\5\15\1\0\1\15\1\0"+
    "\6\15\2\0\12\15\2\0\4\15\40\0\1\15\3\0\17\15\1\0"+
    "\1\15\3\0\2\15\6\0\12\15\13\0\1\15\1\0\1\15\1\0"+
    "\1\15\4\15\12\15\1\0\44\15\4\0\24\15\1\15\22\15\1\0"+
    "\44\15\11\0\1\15\11\0\5\15\4\0\2\15\45\0\112\15\6\15"+
    "\116\15\2\0\46\15\1\0\1\15\5\0\1\15\2\0\53\15\1\15"+
    "\u014d\15\1\0\4\15\2\0\7\15\1\0\1\15\1\0\4\15\2\0"+
    "\51\15\1\0\4\15\2\0\41\15\1\0\4\15\2\0\7\15\1\0"+
    "\1\15\1\0\4\15\2\0\17\15\1\0\71\15\1\0\4\15\2\0"+
    "\103\15\2\0\3\15\11\15\27\0\20\15\20\0\125\15\13\0\1\15"+
    "\u026c\15\2\15\21\15\1\0\32\15\2\15\3\0\113\15\3\15\3\15"+
    "\17\0\15\15\1\0\7\15\13\0\25\15\2\15\11\0\24\15\14\0"+
    "\15\15\1\0\3\15\1\0\2\15\14\0\124\15\3\15\1\15\3\15"+
    "\3\15\2\0\12\15\26\0\13\15\3\15\2\0\12\15\6\0\130\15"+
    "\10\0\53\15\5\0\106\15\12\0\35\15\3\0\14\15\4\0\14\15"+
    "\10\0\2\15\50\15\2\0\5\15\13\0\54\15\4\0\32\15\6\0"+
    "\12\15\46\0\34\15\2\0\2\15\77\15\1\0\35\15\2\0\13\15"+
    "\6\0\12\15\6\0\7\15\1\15\6\15\122\0\114\15\4\0\12\15"+
    "\7\15\12\0\11\15\14\0\164\15\10\0\4\15\70\15\3\0\5\15"+
    "\12\15\3\0\61\15\2\15\100\0\10\15\10\0\3\15\1\15\43\15"+
    "\11\0\347\15\25\0\u011a\15\2\0\6\15\2\0\46\15\2\0\6\15"+
    "\2\0\10\15\1\0\1\15\1\0\1\15\1\0\1\15\1\0\37\15"+
    "\2\0\65\15\1\0\7\15\1\0\1\15\3\0\3\15\1\0\7\15"+
    "\3\0\4\15\2\0\6\15\4\0\15\15\5\0\3\15\1\0\7\15"+
    "\16\0\5\15\30\15\1\12\1\12\5\15\1\0\17\15\2\15\3\15"+
    "\1\0\15\15\1\0\1\15\1\15\12\15\1\0\5\15\5\0\6\15"+
    "\1\0\1\15\13\0\2\15\1\15\15\0\2\15\1\0\15\15\3\0"+
    "\33\15\25\0\15\15\4\0\1\15\3\0\14\15\21\0\1\15\4\0"+
    "\1\15\2\0\12\15\1\0\1\15\3\0\5\15\6\0\1\15\1\0"+
    "\1\15\1\0\1\15\1\0\4\15\1\0\13\15\2\0\4\15\5\0"+
    "\5\15\4\0\1\15\21\0\51\15\u017f\0\4\15\35\0\2\15\u043d\0"+
    "\16\15\117\0\2\15\37\0\12\15\u0193\0\26\15\77\0\4\15\40\0"+
    "\2\15\u0202\0\57\15\1\0\57\15\1\0\205\15\6\0\11\15\5\0"+
    "\4\15\1\0\2\15\46\15\1\0\1\15\5\0\1\15\2\0\70\15"+
    "\7\0\1\15\1\15\16\0\30\15\11\0\7\15\1\0\7\15\1\0"+
    "\7\15\1\0\7\15\1\0\7\15\1\0\7\15\1\0\7\15\1\0"+
    "\7\15\1\0\40\15\57\15\1\15\23\15\u01be\0\3\15\1\0\3\15"+
    "\12\15\2\0\14\15\1\0\17\15\1\15\5\15\2\0\5\15\1\15"+
    "\3\0\126\15\2\0\2\15\2\0\3\15\1\15\132\15\1\15\4\15"+
    "\5\0\51\15\3\0\136\15\21\0\33\15\65\0\20\15\u0200\0\u19b6\15"+
    "\112\0\u51cd\15\63\0\u048d\15\103\0\56\15\2\15\u010d\15\3\15\34\15"+
    "\24\0\60\15\3\0\1\15\12\15\1\15\31\15\7\0\123\15\6\15"+
    "\37\0\11\15\2\0\147\15\2\0\4\15\1\0\4\15\14\0\13\15"+
    "\115\0\60\15\20\0\1\15\7\0\64\15\4\15\10\0\105\15\11\0"+
    "\2\15\12\15\6\0\30\15\3\15\1\15\4\0\56\15\2\15\44\15"+
    "\13\0\1\15\35\15\3\0\101\15\15\15\1\0\13\15\4\0\2\15"+
    "\40\0\67\15\11\0\16\15\2\0\12\15\2\0\4\15\27\15\3\0"+
    "\2\15\4\0\103\15\30\0\3\15\2\15\20\15\2\15\5\15\12\0"+
    "\6\15\2\0\6\15\2\0\6\15\11\0\7\15\1\0\7\15\221\0"+
    "\53\15\1\15\2\15\2\0\12\15\6\0\u2ba4\15\14\0\27\15\4\0"+
    "\61\15\u2104\0\u016e\15\2\0\152\15\46\0\7\15\14\0\5\15\5\0"+
    "\14\15\1\0\15\15\1\0\5\15\1\0\1\15\1\0\2\15\1\0"+
    "\2\15\1\0\154\15\41\0\u016b\15\2\15\20\0\100\15\2\0\66\15"+
    "\50\0\15\15\3\0\20\15\12\15\6\0\7\15\11\0\3\15\2\15"+
    "\30\15\3\15\3\15\1\0\16\15\1\0\1\15\4\0\1\15\1\15"+
    "\2\15\4\0\5\15\1\0\207\15\2\0\1\15\1\0\3\15\1\15"+
    "\6\15\1\0\4\15\12\15\2\15\3\0\2\15\32\15\3\15\1\0"+
    "\1\15\1\0\32\15\1\15\1\0\1\15\1\0\7\15\131\15\3\0"+
    "\6\15\2\0\6\15\2\0\6\15\2\0\3\15\3\0\2\15\3\0"+
    "\2\15\22\0\3\15\4\0\14\15\1\0\32\15\1\0\23\15\1\0"+
    "\2\15\1\0\17\15\2\0\16\15\42\0\173\15\5\0\3\15\75\0"+
    "\65\15\210\0\1\15\202\0\35\15\3\0\61\15\57\0\37\15\21\0"+
    "\33\15\65\0\36\15\1\0\1\15\44\15\4\0\10\15\1\15\5\15"+
    "\52\0\236\15\2\0\12\15\305\0\1\15\u0290\0\6\15\2\0\1\15"+
    "\1\0\54\15\1\0\2\15\3\0\1\15\2\0\27\15\1\0\1\15"+
    "\250\0\26\15\11\0\1\15\32\15\5\0\1\15\100\0\70\15\6\0"+
    "\2\15\100\0\4\15\1\0\2\15\5\0\10\15\1\0\3\15\1\0"+
    "\33\15\4\0\3\15\4\0\1\15\20\0\11\15\7\0\35\15\2\0"+
    "\1\15\160\0\7\15\11\0\66\15\3\0\7\15\26\15\12\0\23\15"+
    "\46\0\4\15\143\0\111\15\u03b7\0\107\15\7\15\30\0\12\15\20\0"+
    "\73\15\2\15\1\15\4\15\16\0\31\15\7\0\12\15\6\0\65\15"+
    "\1\0\12\15\4\15\60\0\2\15\12\0\105\15\4\15\4\0\1\15"+
    "\2\0\12\15\136\0\6\15\u0288\0\1\15\372\0\11\15\167\0\3\15"+
    "\74\0\70\15\10\0\12\15\u0936\0\u036f\15\221\0\143\15\15\0\5\15"+
    "\u0b8b\0\u042f\15\u33d1\0\u0239\15\65\0\2\15\205\0\1\15\101\0\5\15"+
    "\10\0\1\15\u03bb\0\105\15\13\0\57\15\20\0\21\15\u4060\0\2\15"+
    "\u0c9d\0\1\15\u14c5\0\5\15\3\0\26\15\2\0\7\15\36\0\4\15"+
    "\224\0\3\15\u01bb\0\125\15\1\0\107\15\1\0\2\15\2\0\1\15"+
    "\2\0\2\15\2\0\4\15\1\0\14\15\1\0\1\15\1\0\7\15"+
    "\1\0\101\15\1\0\4\15\2\0\10\15\1\0\7\15\1\0\34\15"+
    "\1\0\4\15\1\0\5\15\1\0\1\15\3\0\7\15\1\0\u0154\15"+
    "\2\0\31\15\1\0\31\15\1\0\37\15\1\0\31\15\1\0\37\15"+
    "\1\0\31\15\1\0\37\15\1\0\31\15\1\0\37\15\1\0\31\15"+
    "\1\0\10\15\2\0\62\15\u1600\0\4\15\1\0\33\15\1\0\2\15"+
    "\1\0\1\15\2\0\1\15\1\0\12\15\1\0\4\15\1\0\1\15"+
    "\1\0\1\15\6\0\1\15\4\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\3\15\1\0\2\15\1\0\1\15\2\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\2\15\1\0\1\15"+
    "\2\0\4\15\1\0\7\15\1\0\4\15\1\0\4\15\1\0\1\15"+
    "\1\0\12\15\1\0\21\15\5\0\3\15\1\0\5\15\1\0\21\15"+
    "\u1144\0\ua6d7\15\51\0\u1035\15\13\0\336\15\u3fe2\0\u021e\15\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\15\36\0\140\15\200\0\360\15\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\4\1\2"+
    "\1\6\2\1\1\7\1\10\15\3\1\11\1\12\1\13"+
    "\1\14\1\15\2\1\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\3\0\1\34\2\3\1\35\1\36\14\3\1\37"+
    "\5\3\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\0\1\47\2\3\1\50\1\51\1\52\3\3\1\53"+
    "\3\3\1\54\6\3\1\55\2\3\1\56\1\3\1\57"+
    "\1\60\1\61\1\62\1\3\1\63\1\64\1\3\1\65"+
    "\1\66\1\3\1\67\1\3\1\70\1\71\1\72\1\3"+
    "\1\73\1\74\1\75";

  private static int [] zzUnpackAction() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\72\0\256\0\350\0\72\0\72"+
    "\0\u0122\0\u015c\0\u0196\0\u01d0\0\256\0\256\0\u020a\0\u0244"+
    "\0\u027e\0\u02b8\0\u02f2\0\u032c\0\u0366\0\u03a0\0\u03da\0\u0414"+
    "\0\u044e\0\u0488\0\u04c2\0\u04fc\0\u0536\0\72\0\72\0\u0570"+
    "\0\u05aa\0\u05e4\0\72\0\u061e\0\72\0\72\0\72\0\72"+
    "\0\72\0\72\0\72\0\72\0\72\0\72\0\72\0\72"+
    "\0\u0658\0\u0692\0\u01d0\0\u01d0\0\u06cc\0\u0706\0\u0740\0\256"+
    "\0\u077a\0\u07b4\0\u07ee\0\u0828\0\u0862\0\u089c\0\u08d6\0\u0910"+
    "\0\u094a\0\u0984\0\u09be\0\u09f8\0\256\0\u0a32\0\u0a6c\0\u0aa6"+
    "\0\u0ae0\0\u0b1a\0\72\0\72\0\72\0\72\0\72\0\72"+
    "\0\72\0\u0b54\0\72\0\u0b8e\0\u0bc8\0\256\0\256\0\256"+
    "\0\u0c02\0\u0c3c\0\u0c76\0\256\0\u0cb0\0\u0cea\0\u0d24\0\256"+
    "\0\u0d5e\0\u0d98\0\u0dd2\0\u0e0c\0\u0e46\0\u0e80\0\256\0\u0eba"+
    "\0\u0ef4\0\256\0\u0f2e\0\256\0\256\0\256\0\256\0\u0f68"+
    "\0\256\0\256\0\u0fa2\0\256\0\256\0\u0fdc\0\256\0\u1016"+
    "\0\256\0\256\0\256\0\u1050\0\256\0\256\0\256";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\3\4\1\5\1\6\1\7\1\10\1\11"+
    "\2\2\1\12\1\2\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\5\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\5\1\31\1\32\1\5\1\33\3\5"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\74\0\1\4\74\0"+
    "\4\5\7\0\25\5\33\0\1\6\1\0\1\6\61\0"+
    "\1\11\1\0\1\4\7\11\2\0\56\11\11\0\1\61"+
    "\63\0\1\62\1\0\5\62\1\0\33\62\1\0\4\62"+
    "\3\0\1\62\1\0\2\62\1\0\7\62\3\0\1\63"+
    "\1\0\5\63\1\0\4\63\1\64\26\63\1\0\4\63"+
    "\3\0\1\63\1\0\2\63\1\0\7\63\5\0\4\5"+
    "\7\0\3\5\1\65\21\5\32\0\4\5\7\0\6\5"+
    "\1\66\16\5\32\0\4\5\7\0\5\5\1\67\10\5"+
    "\1\70\6\5\32\0\4\5\7\0\7\5\1\71\10\5"+
    "\1\72\4\5\32\0\4\5\7\0\6\5\1\73\16\5"+
    "\32\0\4\5\7\0\13\5\1\74\4\5\1\75\2\5"+
    "\1\76\1\5\32\0\4\5\7\0\12\5\1\77\5\5"+
    "\1\100\4\5\32\0\4\5\7\0\3\5\1\101\3\5"+
    "\1\102\15\5\32\0\4\5\7\0\4\5\1\103\20\5"+
    "\32\0\4\5\7\0\23\5\1\104\1\5\32\0\4\5"+
    "\7\0\4\5\1\105\1\5\1\106\4\5\1\107\11\5"+
    "\32\0\4\5\7\0\7\5\1\110\15\5\32\0\4\5"+
    "\7\0\12\5\1\111\5\5\1\112\4\5\72\0\1\113"+
    "\1\114\77\0\1\115\63\0\1\116\75\0\1\117\72\0"+
    "\1\120\64\0\1\121\23\0\11\61\1\122\60\61\16\0"+
    "\1\123\60\0\4\5\7\0\4\5\1\124\20\5\32\0"+
    "\4\5\7\0\4\5\1\125\20\5\32\0\4\5\7\0"+
    "\10\5\1\126\14\5\32\0\4\5\7\0\5\5\1\127"+
    "\2\5\1\130\14\5\32\0\4\5\7\0\20\5\1\131"+
    "\4\5\32\0\4\5\7\0\17\5\1\132\5\5\32\0"+
    "\4\5\7\0\7\5\1\133\15\5\32\0\4\5\7\0"+
    "\11\5\1\134\13\5\32\0\4\5\7\0\7\5\1\135"+
    "\15\5\32\0\4\5\7\0\4\5\1\136\20\5\32\0"+
    "\4\5\7\0\20\5\1\137\4\5\32\0\4\5\7\0"+
    "\10\5\1\140\14\5\32\0\4\5\7\0\3\5\1\141"+
    "\4\5\1\142\14\5\32\0\4\5\7\0\14\5\1\143"+
    "\10\5\32\0\4\5\7\0\3\5\1\144\21\5\32\0"+
    "\4\5\7\0\20\5\1\145\4\5\32\0\4\5\7\0"+
    "\7\5\1\146\15\5\32\0\4\5\7\0\24\5\1\147"+
    "\32\0\4\5\7\0\7\5\1\150\15\5\32\0\4\5"+
    "\7\0\20\5\1\151\4\5\25\0\14\61\1\4\55\61"+
    "\5\0\4\5\7\0\5\5\1\152\17\5\32\0\4\5"+
    "\7\0\3\5\1\153\21\5\32\0\4\5\7\0\11\5"+
    "\1\154\13\5\32\0\4\5\7\0\7\5\1\155\15\5"+
    "\32\0\4\5\7\0\16\5\1\156\6\5\32\0\4\5"+
    "\7\0\5\5\1\157\17\5\32\0\4\5\7\0\5\5"+
    "\1\160\17\5\32\0\4\5\7\0\6\5\1\161\16\5"+
    "\32\0\4\5\7\0\13\5\1\162\11\5\32\0\4\5"+
    "\7\0\15\5\1\163\7\5\32\0\4\5\7\0\10\5"+
    "\1\164\14\5\32\0\4\5\7\0\12\5\1\165\12\5"+
    "\32\0\4\5\7\0\3\5\1\166\21\5\32\0\4\5"+
    "\7\0\16\5\1\167\6\5\32\0\4\5\7\0\3\5"+
    "\1\170\21\5\32\0\4\5\7\0\6\5\1\171\16\5"+
    "\32\0\4\5\7\0\17\5\1\172\5\5\32\0\4\5"+
    "\7\0\10\5\1\173\14\5\32\0\4\5\7\0\12\5"+
    "\1\174\12\5\32\0\4\5\7\0\10\5\1\175\14\5"+
    "\32\0\4\5\7\0\22\5\1\176\2\5\32\0\4\5"+
    "\7\0\5\5\1\177\17\5\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4234];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\2\1\2\11\25\1\2\11"+
    "\3\1\1\11\1\1\14\11\3\0\27\1\7\11\1\0"+
    "\1\11\54\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  StringBuffer string = new StringBuffer();

  private boolean debug_mode;
  public  boolean debug()            { return debug_mode; }
  public  void    debug(boolean mode){ debug_mode = mode; }

//  Function print_lexeme
  private void print_lexeme(int type, Object value){
    if(!debug()){ return; }

    System.out.print("<");
    switch(type){
      case sym.LET:
        System.out.print("LET"); break;
      case sym.EQUAL:
        System.out.print(":="); break;
      case sym.SEMICOL:
        System.out.print(";"); break;
      case sym.PLUS:
        System.out.print("+"); break;
      case sym.MINUS:
        System.out.print("-"); break;
      case sym.MULT:
        System.out.print("*"); break;
      case sym.DIV:
        System.out.print("/"); break;
      case sym.LPAREN:
        System.out.print("("); break;
      case sym.RPAREN:
        System.out.print(")"); break;
      case sym.INTEGER:
        System.out.printf("INT %d", value); break;
      case sym.IDENTIFIER:
        System.out.printf("IDENT %s", value); break;
      case sym.MAIN:
        System.out.print("main"); break;
      case sym.LBRA:
            System.out.print("{"); break;
      case sym.RBRA:
            System.out.print("}"); break;
      case sym.PRINT:
            System.out.print("print"); break;
      case sym.CHAR:
            System.out.printf("CHAR %c", value); break;


    }
    System.out.print(">  ");
  }

  private Symbol symbol(int type) {
    print_lexeme(type, null);
    return new Symbol(type, yyline, yycolumn);
  }
  private Symbol symbol(int type, Object value) {
    print_lexeme(type, value);
    return new Symbol(type, yyline, yycolumn, value);
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2836) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("file:" + (yyline+1) +
    ":0: Error: Invalid input '" + yytext()+"'");
  return symbol(sym.BADCHAR);
            }
          case 62: break;
          case 2: 
            { /* do nothing */
            }
          case 63: break;
          case 3: 
            { return symbol(sym.IDENTIFIER, yytext());
            }
          case 64: break;
          case 4: 
            { return symbol(sym.INTEGER,Integer.parseInt(yytext()));
            }
          case 65: break;
          case 5: 
            { return symbol(sym.UNDERSCORE);
            }
          case 66: break;
          case 6: 
            { return symbol(sym.DIV);
            }
          case 67: break;
          case 7: 
            { return symbol(sym.TRUE);
            }
          case 68: break;
          case 8: 
            { return symbol(sym.FALSE);
            }
          case 69: break;
          case 9: 
            { return symbol(sym.COLON);
            }
          case 70: break;
          case 10: 
            { return symbol(sym.EQ);
            }
          case 71: break;
          case 11: 
            { return symbol(sym.SEMICOL);
            }
          case 72: break;
          case 12: 
            { return symbol(sym.COMMA);
            }
          case 73: break;
          case 13: 
            { return symbol(sym.EXCLAM);
            }
          case 74: break;
          case 14: 
            { return symbol(sym.RCROCHET);
            }
          case 75: break;
          case 15: 
            { return symbol(sym.LCROCHET);
            }
          case 76: break;
          case 16: 
            { return symbol(sym.QUESTION);
            }
          case 77: break;
          case 17: 
            { return symbol(sym.PLUS);
            }
          case 78: break;
          case 18: 
            { return symbol(sym.MINUS);
            }
          case 79: break;
          case 19: 
            { return symbol(sym.MULT);
            }
          case 80: break;
          case 20: 
            { return symbol(sym.EXPO);
            }
          case 81: break;
          case 21: 
            { return symbol(sym.LPAREN);
            }
          case 82: break;
          case 22: 
            { return symbol(sym.RPAREN);
            }
          case 83: break;
          case 23: 
            { return symbol(sym.LBRA);
            }
          case 84: break;
          case 24: 
            { return symbol(sym.RBRA);
            }
          case 85: break;
          case 25: 
            { return symbol(sym.DOT);
            }
          case 86: break;
          case 26: 
            { return symbol(sym.LAGRA);
            }
          case 87: break;
          case 27: 
            { return symbol(sym.RAGRA);
            }
          case 88: break;
          case 28: 
            { return symbol(sym.STRING);
            }
          case 89: break;
          case 29: 
            { return symbol(sym.IN);
            }
          case 90: break;
          case 30: 
            { return symbol(sym.IF);
            }
          case 91: break;
          case 31: 
            { return symbol(sym.FI);
            }
          case 92: break;
          case 32: 
            { return symbol(sym.DOUBLE_COLON);
            }
          case 93: break;
          case 33: 
            { return symbol(sym.EQUAL);
            }
          case 94: break;
          case 34: 
            { return symbol(sym.IMPL);
            }
          case 95: break;
          case 35: 
            { return symbol(sym.DIFF);
            }
          case 96: break;
          case 36: 
            { return symbol(sym.AND);
            }
          case 97: break;
          case 37: 
            { return symbol(sym.OR);
            }
          case 98: break;
          case 38: 
            { return symbol(sym.INFEQ);
            }
          case 99: break;
          case 39: 
            { return symbol(sym.CHAR);
            }
          case 100: break;
          case 40: 
            { return symbol(sym.TYPE_INT);
            }
          case 101: break;
          case 41: 
            { return symbol(sym.LEN);
            }
          case 102: break;
          case 42: 
            { return symbol(sym.LET);
            }
          case 103: break;
          case 43: 
            { return symbol(sym.TOP);
            }
          case 104: break;
          case 44: 
            { return symbol(sym.TYPE_RAT);
            }
          case 105: break;
          case 45: 
            { return symbol(sym.SEQ);
            }
          case 106: break;
          case 46: 
            { return symbol(sym.MAIN);
            }
          case 107: break;
          case 47: 
            { return symbol(sym.LOOP);
            }
          case 108: break;
          case 48: 
            { return symbol(sym.ELSE);
            }
          case 109: break;
          case 49: 
            { return symbol(sym.TDEF);
            }
          case 110: break;
          case 50: 
            { return symbol(sym.THEN);
            }
          case 111: break;
          case 51: 
            { return symbol(sym.POOL);
            }
          case 112: break;
          case 52: 
            { return symbol(sym.READ);
            }
          case 113: break;
          case 53: 
            { return symbol(sym.DICT);
            }
          case 114: break;
          case 54: 
            { return symbol(sym.TYPE_CHAR);
            }
          case 115: break;
          case 55: 
            { return symbol(sym.FDEF);
            }
          case 116: break;
          case 56: 
            { return symbol(sym.TYPE_BOOL);
            }
          case 117: break;
          case 57: 
            { return symbol(sym.ALIAS);
            }
          case 118: break;
          case 58: 
            { return symbol(sym.PRINT);
            }
          case 119: break;
          case 59: 
            { return symbol(sym.TYPE_FLOAT);
            }
          case 120: break;
          case 60: 
            { return symbol(sym.BREAK);
            }
          case 121: break;
          case 61: 
            { return symbol(sym.RETURN);
            }
          case 122: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
