
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUS = 6;
  public static final int BADCHAR = 14;
  public static final int RPAREN = 11;
  public static final int EQUAL = 4;
  public static final int CHAR = 24;
  public static final int TYPE_INT = 19;
  public static final int RBRA = 12;
  public static final int TYPE_CHAR = 18;
  public static final int IDENTIFIER = 2;
  public static final int TRUE = 22;
  public static final int LBRA = 13;
  public static final int LPAREN = 10;
  public static final int EOF = 0;
  public static final int MULT = 8;
  public static final int MAIN = 15;
  public static final int DIV = 9;
  public static final int SEMICOL = 5;
  public static final int FALSE = 23;
  public static final int MINUS = 7;
  public static final int PRINT = 16;
  public static final int error = 1;
  public static final int LET = 3;
  public static final int TYPE_RAT = 21;
  public static final int TYPE_FLOAT = 20;
  public static final int INTEGER = 25;
  public static final int TYPE_BOOL = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "LET",
  "EQUAL",
  "SEMICOL",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "LPAREN",
  "RPAREN",
  "RBRA",
  "LBRA",
  "BADCHAR",
  "MAIN",
  "PRINT",
  "TYPE_BOOL",
  "TYPE_CHAR",
  "TYPE_INT",
  "TYPE_FLOAT",
  "TYPE_RAT",
  "TRUE",
  "FALSE",
  "CHAR",
  "INTEGER"
  };
}

