
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 43;
  public static final int RCROCHET = 13;
  public static final int MULT = 8;
  public static final int CHAR = 59;
  public static final int POOL = 34;
  public static final int LBRA = 31;
  public static final int IMPL = 22;
  public static final int INTEGER = 60;
  public static final int EXCLAM = 19;
  public static final int LPAREN = 28;
  public static final int EXPO = 25;
  public static final int BADCHAR = 32;
  public static final int LAGRA = 17;
  public static final int MINUS = 7;
  public static final int RPAREN = 29;
  public static final int AND = 20;
  public static final int TDEF = 47;
  public static final int IN = 46;
  public static final int OR = 21;
  public static final int COMMA = 14;
  public static final int SEMICOL = 5;
  public static final int FI = 38;
  public static final int DIV = 9;
  public static final int TYPE_INT = 54;
  public static final int LOOP = 33;
  public static final int PLUS = 6;
  public static final int MAIN = 40;
  public static final int IF = 35;
  public static final int DOT = 11;
  public static final int EOF = 0;
  public static final int RETURN = 51;
  public static final int EQUAL = 4;
  public static final int TRUE = 57;
  public static final int error = 1;
  public static final int INFEQ = 26;
  public static final int LCROCHET = 12;
  public static final int RBRA = 30;
  public static final int RAGRA = 18;
  public static final int FDEF = 48;
  public static final int BREAK = 39;
  public static final int TYPE_RAT = 56;
  public static final int TYPE_FLOAT = 55;
  public static final int EQ = 23;
  public static final int TYPE_CHAR = 53;
  public static final int TOP = 44;
  public static final int COLON = 15;
  public static final int DICT = 42;
  public static final int ELSE = 37;
  public static final int READ = 50;
  public static final int DOUBLE_COLON = 16;
  public static final int LET = 3;
  public static final int THEN = 36;
  public static final int UNDERSCORE = 10;
  public static final int STRING = 61;
  public static final int LEN = 45;
  public static final int QUESTION = 27;
  public static final int ALIAS = 49;
  public static final int DIFF = 24;
  public static final int FALSE = 58;
  public static final int TYPE_BOOL = 52;
  public static final int PRINT = 41;
  public static final int IDENTIFIER = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "LET",
  "EQUAL",
  "SEMICOL",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "UNDERSCORE",
  "DOT",
  "LCROCHET",
  "RCROCHET",
  "COMMA",
  "COLON",
  "DOUBLE_COLON",
  "LAGRA",
  "RAGRA",
  "EXCLAM",
  "AND",
  "OR",
  "IMPL",
  "EQ",
  "DIFF",
  "EXPO",
  "INFEQ",
  "QUESTION",
  "LPAREN",
  "RPAREN",
  "RBRA",
  "LBRA",
  "BADCHAR",
  "LOOP",
  "POOL",
  "IF",
  "THEN",
  "ELSE",
  "FI",
  "BREAK",
  "MAIN",
  "PRINT",
  "DICT",
  "SEQ",
  "TOP",
  "LEN",
  "IN",
  "TDEF",
  "FDEF",
  "ALIAS",
  "READ",
  "RETURN",
  "TYPE_BOOL",
  "TYPE_CHAR",
  "TYPE_INT",
  "TYPE_FLOAT",
  "TYPE_RAT",
  "TRUE",
  "FALSE",
  "CHAR",
  "INTEGER",
  "STRING"
  };
}

